// @generated by protobuf-ts 2.6.0 with parameter long_type_string
// @generated from protobuf file "ibc/applications/interchain_accounts/host/v1/query.proto" (package "ibc.applications.interchain_accounts.host.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Query } from "./query";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { QueryParamsResponse } from "./query";
import type { QueryParamsRequest } from "./query";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Query provides defines the gRPC querier service.
 *
 * @generated from protobuf service ibc.applications.interchain_accounts.host.v1.Query
 */
export interface IQueryClient {
    /**
     * Params queries all parameters of the ICA host submodule.
     *
     * @generated from protobuf rpc: Params(ibc.applications.interchain_accounts.host.v1.QueryParamsRequest) returns (ibc.applications.interchain_accounts.host.v1.QueryParamsResponse);
     */
    params(input: QueryParamsRequest, options?: RpcOptions): UnaryCall<QueryParamsRequest, QueryParamsResponse>;
}
/**
 * Query provides defines the gRPC querier service.
 *
 * @generated from protobuf service ibc.applications.interchain_accounts.host.v1.Query
 */
export class QueryClient implements IQueryClient, ServiceInfo {
    typeName = Query.typeName;
    methods = Query.methods;
    options = Query.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Params queries all parameters of the ICA host submodule.
     *
     * @generated from protobuf rpc: Params(ibc.applications.interchain_accounts.host.v1.QueryParamsRequest) returns (ibc.applications.interchain_accounts.host.v1.QueryParamsResponse);
     */
    params(input: QueryParamsRequest, options?: RpcOptions): UnaryCall<QueryParamsRequest, QueryParamsResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<QueryParamsRequest, QueryParamsResponse>("unary", this._transport, method, opt, input);
    }
}
